// Auto-generated list of carousel images
// Images renamed with descriptive filenames for better organization

const carouselImages = [
    {src: 'carousel_images/billy-elliott-01.jpeg', caption: 'Billy Elliott \\'},
    {src: 'carousel_images/elf-the-musical-01.jpeg', caption: 'Elf the Musical \\'},
    {src: 'carousel_images/mama-mia-01.jpeg', caption: 'Mama Mia \\'},
    {src: 'carousel_images/bullets-over-broadway-01.jpeg', caption: 'Bullets over Broadway \\'},
    {src: 'carousel_images/olaf-custom-puppet-01.jpeg', caption: 'Olaf - custom puppet\\'},
    {src: 'carousel_images/dragon-puppet-magic-books-01.jpeg', caption: 'Dragon Puppet - Magic Books\\'},
    {src: 'carousel_images/custom-dancewear-01.jpeg', caption: 'Custom Dance wear\\'},
    {src: 'carousel_images/giant-wing-painting-az-opera-01.jpeg', caption: 'Giant wing painting for AZ Opera\\'},
    {src: 'carousel_images/olaf-melting-01.jpeg', caption: 'Olaf - melting\\'},
    {src: 'carousel_images/magic-books-dragon-01.jpeg', caption: 'Magic Books Dragon \\'},
    {src: 'carousel_images/gypsy-01.jpeg', caption: 'Gypsy\\'},
    {src: 'carousel_images/custom-bellydance-wear-01.jpeg', caption: 'Custom Bellydance wear\\'},
    {src: 'carousel_images/costume-design-01.jpeg', caption: ''},
    {src: 'carousel_images/pippin-01.jpeg', caption: 'Pippin\\'},
    {src: 'carousel_images/roxie-and-velma.jpeg', caption: 'Roxie & Velma\\'},
    {src: 'carousel_images/joey-sorge-walt-disney-when-you-wish.jpeg', caption: 'Joey Sorge as Walt Disney in When You Wish\\'},
    {src: 'carousel_images/santa-mrs-claus-elf-the-musical.jpeg', caption: 'Santa and Mrs. Claus - Elf the Musical\\'},
    {src: 'carousel_images/westside-story-01.jpeg', caption: 'Westside Story\\'},
    {src: 'carousel_images/costume-design-02.jpeg', caption: ''},
    {src: 'carousel_images/once-01.jpeg', caption: 'Once \\'},
    {src: 'carousel_images/costume-design-03.jpeg', caption: ''},
    {src: 'carousel_images/jersey-boys-angels.jpeg', caption: 'Jersey Boys Angels\\'},
    {src: 'carousel_images/little-shop-of-horrors-01.jpeg', caption: 'Little Shop of Horrors \\'},
    {src: 'carousel_images/costume-design-04.jpeg', caption: '{\\\\\\'},
    {src: 'carousel_images/mimis-boots-rent.jpeg', caption: 'Mimi\\u2019s boots - Rent\\'},
    {src: 'carousel_images/rent-angels-dress.jpeg', caption: 'Rent - Angel\\u2019s Dress\\'},
    {src: 'carousel_images/elf-the-musical-02.jpeg', caption: 'Elf the Musical \\'},
    {src: 'carousel_images/jersey-boys-01.jpeg', caption: 'Jersey Boys\\'},
    {src: 'carousel_images/godspell-01.jpeg', caption: 'Godspell \\'},
    {src: 'carousel_images/mama-mia-02.jpeg', caption: 'Mama Mia\\'},
    {src: 'carousel_images/mama-mia-03.jpeg', caption: 'Mama Mia\\'},
    {src: 'carousel_images/costume-portfolio-header.jpeg', caption: ''},
    {src: 'carousel_images/pippin-and-charlemagne.jpeg', caption: 'Pippin & Charlemagne\\'},
    {src: 'carousel_images/giant-wing-painting-az-opera-02.jpeg', caption: 'Giant wing painting for AZ Opera\\'},
    {src: 'carousel_images/olaf-custom-puppet-02.jpeg', caption: 'Olaf - custom puppet\\'},
    {src: 'carousel_images/beehive-01.jpeg', caption: 'Beehive\\'},
    {src: 'carousel_images/once-02.jpeg', caption: 'Once\\'},
    {src: 'carousel_images/in-the-heights-01.jpeg', caption: 'In the Heights\\'},
    {src: 'carousel_images/beehive-02.jpeg', caption: 'Beehive \\'},
    {src: 'carousel_images/westside-story-the-jets-01.jpeg', caption: 'Westside Story - The Jets\\'},
    {src: 'carousel_images/hand-to-god-puppetry-01.jpeg', caption: 'Hand to God - puppetry\\'},
    {src: 'carousel_images/roxie-chicago.jpeg', caption: 'Roxie - Chicago\\'},
    {src: 'carousel_images/magic-books-dragon-02.jpeg', caption: 'Magic Books Dragon \\'},
    {src: 'carousel_images/westside-story-the-jets-02.jpeg', caption: 'Westside Story - The Jets\\'},
    {src: 'carousel_images/once-03.jpeg', caption: 'Once\\'},
    {src: 'carousel_images/custom-bellydance-wear-02.jpeg', caption: 'Custom Bellydance wear\\'},
    {src: 'carousel_images/costume-design-05.jpeg', caption: '{\\\\\\'},
    {src: 'carousel_images/westside-story-02.jpeg', caption: 'Westside Story\\'},
    {src: 'carousel_images/custom-bellydance-bra-and-belt.jpeg', caption: 'Custom Bellydance Bra and Belt\\'},
    {src: 'carousel_images/childsplay-goodnight-moon-mouse-01.jpeg', caption: 'Childsplay\\u2019s Goodnight Moon Mouse\\'},
    {src: 'carousel_images/billy-elliott-02.jpeg', caption: 'Billy Elliot\\'},
    {src: 'carousel_images/childsplay-goodnight-moon-mouse-02.jpeg', caption: 'Childsplay\\u2019s Goodnight Moon Mouse\\'},
    {src: 'carousel_images/custom-dancewear-02.jpeg', caption: 'Custom Dance wear\\'},
    {src: 'carousel_images/all-night-strut.jpeg', caption: 'All Night Strut\\'},
    {src: 'carousel_images/jersey-boys-02.jpeg', caption: 'Jersey Boys\\'},
    {src: 'carousel_images/godspell-02.jpeg', caption: 'Godspell\\'},
    {src: 'carousel_images/elf-the-musical-03.jpeg', caption: 'Elf the Musical \\'},
    {src: 'carousel_images/aretha-franklin-beehive.jpeg', caption: 'Aretha Franklin - Beehive\\'},
    {src: 'carousel_images/costume-design-06.jpeg', caption: ''},
    {src: 'carousel_images/costume-design-07.jpeg', caption: ''},
    {src: 'carousel_images/mama-mia-04.jpeg', caption: 'Mama Mia \\'},
    {src: 'carousel_images/pippin-02.jpeg', caption: 'Pippin\\'},
    {src: 'carousel_images/westside-story-03.jpeg', caption: 'Westside Story \\'},
    {src: 'carousel_images/beehive-03.jpeg', caption: 'Beehive \\'},
    {src: 'carousel_images/tina-turner-beehive.jpeg', caption: 'Tina Turner - Beehive\\'},
    {src: 'carousel_images/one-man-two-guvnors.jpeg', caption: 'One Man Two Guv\\'},
    {src: 'carousel_images/roxie-02.jpeg', caption: 'Roxie\\'},
    {src: 'carousel_images/magic-books-dragon-03.jpeg', caption: 'Magic Books Dragon \\'},
    {src: 'carousel_images/costume-design-08.jpeg', caption: ''},
    {src: 'carousel_images/hand-to-god-puppetry-02.jpeg', caption: 'Hand to God - puppetry\\'},
    {src: 'carousel_images/olaf-melting-02.jpeg', caption: 'Olaf - melting\\'},
    {src: 'carousel_images/when-you-wish-01.jpeg', caption: 'When You Wish\\'},
    {src: 'carousel_images/dora-explorer-puppets.jpeg', caption: 'Dora the Explorer Puppets\\'},
    {src: 'carousel_images/costume-design-09.jpeg', caption: ''},
    {src: 'carousel_images/when-you-wish-02.jpeg', caption: 'When you wish\\'},
    {src: 'carousel_images/costume-design-10.jpeg', caption: ''},
];

